### ISSUE TITLE
Iran also forces safesearch when using Bing

### ISSUE THREAD

**Issue by cptxxx** [AliAlmasi/unforce-safesearch#1]
Bing search engine also has the ability to force the safesearch using dns (with `strict.bing.com` domain - IP: 204.79.197.220)

Iran also uses this IP when someone requests for `bing.com`  
![image](https://github.com/AliAlmasi/unforce-safesearch/assets/95831388/2b9d40d9-08ee-4f6a-ba38-1c23e79b15c3)

This is happening in Iran, while the `bing.com` domain points to IP: 13.107.21.200 ([google dns used](https://www.nslookup.io/domains/bing.com/dns-records/#google))  
![image](https://github.com/AliAlmasi/unforce-safesearch/assets/95831388/ac90b21e-90cd-4c3d-8199-27558f928743)

**Comment by AliAlmasi** [comment]
I suppose you're right. I checked this with both Iranian poisoned DNS server & Google DNS.

I'll add this to the readme file. Thanks a bunch.
